#!/usr/bin/env node
/**
 * dev-build.js - Fast development build for SoH Tracker.
 *
 * Does what `yarn buildDev` does via gulp, but with a direct file copy.
 * Produces dev/ in ~5 seconds instead of 5+ minutes.
 *
 * What it does:
 *   1. Mirror src/ -> dev/
 *   2. Copy each node_modules/<dep>/src -> dev/<DepName>/
 *   3. Copy logic/ -> dev/logic/
 *   4. Copy soh-integration/mappings/ -> dev/soh-integration/mappings/
 *
 * Run: node soh-integration/dev-build.js
 */

'use strict';

const fs = require('node:fs');
const fsp = require('node:fs').promises;
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const DEV = path.join(ROOT, 'dev');
const LOGIC = path.join(ROOT, 'logic');
const MODS = path.join(ROOT, 'node_modules');
const INTEG_MAPPINGS = path.join(ROOT, 'soh-integration', 'mappings');

// ---------------------------------------------------------------------------
// ES-module import transformer
//
// Modern Chromium dropped support for `import X from "foo.html" assert {type:
// "html"}` style import assertions. Track-OOT's emcJS uses them for HTML, CSS,
// JSON siblings. Their gulp build rewrites these into inline template
// strings. This is a straight port of
// node_modules/emcjs/src/_build_tools/sourceImport.js :: augmentFile()
// ---------------------------------------------------------------------------

const HTMLTemplatePath = 'util/html/template/HTMLTemplate.js';
const CSSTemplatePath  = 'util/html/template/CSSTemplate.js';
const LNBR_SEQ = /(?:\r\n|\n|\r)/g;
const IMPORT_SCRIPT = /^\s*import(?:\s+([a-zA-Z0-9_$]+)\s+from)?\s+"([^"]+)"\s*;?$/;
const IMPORT_ASSERT = /^\s*import\s+([a-zA-Z0-9_$]+)\s+from\s+"([^"]+)"\s+assert\s+\{\s*type:\s*"([^"]+)"\s*\}\s*;?$/;

function normalizePath(p) { return p.replace(/\\/g, '/'); }

function transformJSSource(emcJSPrefix, sourcePath, fileContent) {
    const sourceDir = path.dirname(sourcePath);
    const importedHTML = [];
    const importedCSS = [];
    const importedJSON = [];
    const importedJSONFolder = [];

    const lines = fileContent.split(LNBR_SEQ).map((line) => {
        const m = IMPORT_ASSERT.exec(line);
        if (m) {
            const [, name, contentPath, assertType] = m;
            if (assertType === 'html')        { importedHTML.push({ name, contentPath }); return null; }
            if (assertType === 'css')         { importedCSS.push({ name, contentPath }); return null; }
            if (assertType === 'json')        { importedJSON.push({ name, contentPath }); return null; }
            if (assertType === 'json-folder') { importedJSONFolder.push({ name, contentPath }); return null; }
            return line;
        }
        const s = IMPORT_SCRIPT.exec(line);
        if (s) {
            const [, name, p] = s;
            if (!p.endsWith('.js')) {
                return name == null ? `import "${p}.js";` : `import ${name} from "${p}.js";`;
            }
        }
        return line;
    }).filter((x) => x != null).join('\n');

    if (!importedHTML.length && !importedCSS.length && !importedJSON.length && !importedJSONFolder.length) {
        return lines;
    }

    let prefix = '/* ===================== AUTOGENERATED SOURCE IMPORT ===================== */\n\n';

    if (importedHTML.length) {
        const modulePath = normalizePath(`${emcJSPrefix}/${HTMLTemplatePath}`);
        prefix += `import Template from "${modulePath}";\n\n`;
        for (const { name, contentPath } of importedHTML) {
            const resolved = path.resolve(sourceDir, contentPath);
            if (fs.existsSync(resolved)) {
                const fc = fs.readFileSync(resolved).toString();
                prefix += `const ${name} = new Template(\`\n${fc.replace(/\\/g, '\\\\').split('\n').map((l) => '    ' + l).join('\n')}\n\`);\n`;
            }
        }
        prefix += '\n';
    }

    if (importedCSS.length) {
        const modulePath = normalizePath(`${emcJSPrefix}/${CSSTemplatePath}`);
        prefix += `import GlobalStyle from "${modulePath}";\n\n`;
        for (const { name, contentPath } of importedCSS) {
            const resolved = path.resolve(sourceDir, contentPath);
            if (fs.existsSync(resolved)) {
                const fc = fs.readFileSync(resolved).toString();
                prefix += `const ${name} = new GlobalStyle(\`\n${fc.replace(/\\/g, '\\\\').split('\n').map((l) => '    ' + l).join('\n')}\n\`);\n`;
            }
        }
        prefix += '\n';
    }

    if (importedJSON.length) {
        for (const { name, contentPath } of importedJSON) {
            const resolved = path.resolve(sourceDir, contentPath);
            if (fs.existsSync(resolved)) {
                const fc = fs.readFileSync(resolved).toString();
                prefix += `const ${name} = ${fc.replace(/\\/g, '\\\\')};\n`;
            }
        }
        prefix += '\n';
    }

    if (importedJSONFolder.length) {
        for (const { name, contentPath } of importedJSONFolder) {
            const resolved = path.resolve(sourceDir, contentPath);
            if (fs.existsSync(resolved)) {
                const typeDefs = [];
                for (const filePath of fs.readdirSync(resolved)) {
                    const full = path.resolve(resolved, filePath);
                    if (!fs.existsSync(full)) continue;
                    const parsed = path.parse(filePath);
                    const innerName = parsed.name;
                    const fc = fs.readFileSync(full).toString();
                    try {
                        JSON.parse(fc);
                        typeDefs.push(`    ${innerName}: ${fc.replace(/\\/g, '\\\\').split('\n').map((l) => '    ' + l).join('\n').slice(4)}`);
                    } catch (_) { /* ignore invalid JSON */ }
                }
                prefix += `const ${name} = {\n${typeDefs.join(',\n')}\n};\n`;
            }
        }
        prefix += '\n';
    }

    prefix += '/* ======================================================================= */\n\n';
    return prefix + lines;
}

/**
 * Generate /i18n/_meta.json from .lang file headers.
 * Port of emcjs/_build_tools/LanguageManager.js.
 */
function buildI18nMeta(i18nDir) {
    if (!fs.existsSync(i18nDir)) return;
    const extractors = [
        { re: /#\s*@([^\s]+)\s*(.+)\s*/,        func: (r, m) => { r[m[1]] = m[2]; } },
        { re: /#\s*fragment:\s*(.+)\.([^.]+)\s*/, func: (r, m) => {
            r.fragments = r.fragments ?? [];
            r.fragments.push({ type: m[2], name: m[1] });
        }},
    ];
    const LNBR = /(?:\r\n|\n|\r)/g;
    const meta = {};
    for (const entry of fs.readdirSync(i18nDir)) {
        if (!entry.endsWith('.lang')) continue;
        const ref = path.basename(entry, '.lang');
        const content = fs.readFileSync(path.join(i18nDir, entry), 'utf8');
        const result = { label: ref };
        for (const line of content.split(LNBR)) {
            for (const { re, func } of extractors) {
                const m = re.exec(line);
                if (m) { func(result, m); break; }
            }
        }
        meta[ref] = result;
    }
    const metaPath = path.join(i18nDir, '_meta.json');
    fs.writeFileSync(metaPath, JSON.stringify(meta, null, 4));
    console.log(`[dev-build] wrote i18n/_meta.json (${Object.keys(meta).length} languages)`);
}

/**
 * Walk a directory copying files, transforming .js ES module imports in place.
 */
async function copyTree(srcDir, dstDir, emcJSPrefix) {
    await fsp.mkdir(dstDir, { recursive: true });
    const entries = await fsp.readdir(srcDir, { withFileTypes: true });
    await Promise.all(entries.map(async (entry) => {
        const s = path.join(srcDir, entry.name);
        const d = path.join(dstDir, entry.name);
        if (entry.isDirectory()) {
            await copyTree(s, d, emcJSPrefix);
        } else if (entry.isFile()) {
            if (entry.name.endsWith('.js')) {
                const content = await fsp.readFile(s, 'utf8');
                const transformed = transformJSSource(emcJSPrefix, s, content);
                await fsp.writeFile(d, transformed, 'utf8');
            } else {
                await fsp.copyFile(s, d);
            }
        }
    }));
}

// Mapping of import-path aliases -> node_modules package src folder.
// Matches gulpfile.js MODULE_PATHS.
const DEP_MAP = [
    { alias: 'emcJS',         pkg: 'emcjs' },
    { alias: 'GameTrackerJS', pkg: 'gametrackerjs' },
    { alias: 'JSEditors',     pkg: 'jseditors' },
    { alias: 'rtc',           pkg: 'rtcclient' },
    { alias: 'ArchipelagoJS', pkg: 'archipelagojs' },
];

async function rmrf(target) {
    try {
        await fsp.rm(target, { recursive: true, force: true });
    } catch (_) {}
}

async function copyDir(src, dst) {
    await fsp.mkdir(dst, { recursive: true });
    await fsp.cp(src, dst, { recursive: true, force: true });
}

function mustExist(p, label) {
    if (!fs.existsSync(p)) {
        console.error(`ERROR: missing ${label}: ${p}`);
        process.exit(1);
    }
}

async function main() {
    const clean = process.argv.includes('--clean');

    console.log(`[dev-build] ROOT: ${ROOT}`);

    mustExist(SRC, 'src/');
    mustExist(MODS, 'node_modules/ (run `yarn install` first)');
    mustExist(LOGIC, 'logic/');

    if (clean) {
        console.log('[dev-build] cleaning dev/');
        await rmrf(DEV);
    }

    await fsp.mkdir(DEV, { recursive: true });

    const start = Date.now();

    console.log('[dev-build] copying src/ -> dev/ (with import transform)');
    await copyTree(SRC, DEV, '/emcJS');

    console.log('[dev-build] copying logic/ -> dev/logic/');
    await copyDir(LOGIC, path.join(DEV, 'logic'));

    for (const { alias, pkg } of DEP_MAP) {
        const srcDir = path.join(MODS, pkg, 'src');
        const dstDir = path.join(DEV, alias);
        if (!fs.existsSync(srcDir)) {
            console.warn(`[dev-build] skip ${alias} - ${srcDir} not found`);
            continue;
        }
        console.log(`[dev-build] copying ${pkg}/src -> dev/${alias}/ (with import transform)`);
        await copyTree(srcDir, dstDir, '/emcJS');
    }

    // Copy soh-integration mappings so the renderer can fetch them
    if (fs.existsSync(INTEG_MAPPINGS)) {
        const dstMap = path.join(DEV, 'soh-integration', 'mappings');
        await fsp.mkdir(path.dirname(dstMap), { recursive: true });
        console.log('[dev-build] copying soh-integration/mappings -> dev/');
        await copyDir(INTEG_MAPPINGS, dstMap);
    }

    // Generate i18n/_meta.json from .lang headers
    buildI18nMeta(path.join(DEV, 'i18n'));

    const ms = Date.now() - start;
    console.log(`[dev-build] done in ${(ms / 1000).toFixed(1)}s`);

    // Stats
    let files = 0, bytes = 0;
    function walk(dir) {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            const p = path.join(dir, entry.name);
            if (entry.isDirectory()) walk(p);
            else if (entry.isFile()) { files++; bytes += fs.statSync(p).size; }
        }
    }
    walk(DEV);
    console.log(`[dev-build] ${files.toLocaleString()} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`);
}

main().catch((err) => {
    console.error('[dev-build] failed:', err);
    process.exit(1);
});
