import SavestateConverter from "/GameTrackerJS/savestate/SavestateConverter.js";
import "./StateConverter0.js";
import "./StateConverter1.js";
import "./StateConverter2.js";
import "./StateConverter3.js";
import "./StateConverter4.js";
import "./StateConverter5.js";
import "./StateConverter6.js";
import "./StateConverter7.js";
import "./StateConverter8.js";
import "./StateConverter9.js";
import "./StateConverter10.js";
import "./StateConverter11.js";
import "./StateConverter12.js";
import "./StateConverter13.js";
import "./StateConverter14.js";
import "./StateConverter15.js";
import "./StateConverter16.js";
import "./StateConverter17.js";
import "./StateConverter18.js";
import "./StateConverter19.js";
import "./StateConverter20.js";
import "./StateConverter21.js";
import "./StateConverter22.js";
import "./StateConverter23.js";
import "./StateConverter24.js";
import "./StateConverter25.js";
// ---

SavestateConverter.offset = 0;
