import "./augment/AugmentOptions.js";
import "./augment/AugmentDungeonState.js";
import "./augment/AugmentDungeonShortcuts.js";
import "./augment/AugmentZoraLetter.js";
import "./augment/AugmentZeldaLetter.js";
import "./augment/AugmentReachEpona.js";
import "./augment/AugmentOcarinaSongNotes.js";
import "./augment/AugmentTotalHearts.js";
import "./augment/AugmentBuyables.js";
